"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path" : "./crowdin-work/"
"base_url" : "https://api.crowdin.com"
"preserve_hierarchy": true

files: [
 {
  "source" : "%repository.name%/main.ini",
  "translation" : "%repository.name%/%locale%.ini",
  "skip_untranslated_strings" : true
 },
 {
  "source" : "%repository.name%/README.md",
  "translation" : "%repository.name%/README-%two_letters_code%.md",
  "skip_untranslated_files" : true
 }
]
