name: Translation

on:
  push:
    branches:
      - main
    paths:
      - README.md
      - data/locale/en-US.ini

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare source file
        run: |
          ./.github/files/make-crowdin.sh ${{ github.event.repository.name }}

      - name: Crowdin action
        uses: crowdin/github-action@1.4.9
        with:
          upload_translations: false
        env:
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
